# coding=utf-8
CodeList = [
    {"From": "ACX", "TO": "NAY"},
    {"From": "AVA", "TO": "NAY"},
    {"From": "BAV", "TO": "NAY"},
    {"From": "CTU", "TO": "NAY"},
    {"From": "CTU", "TO": "SJW"},
    {"From": "DAT", "TO": "NAY"},
    {"From": "DLC", "TO": "NAY"},
    {"From": "DLC", "TO": "SJW"},
    {"From": "DSN", "TO": "NAY"},
    {"From": "DSN", "TO": "NKG"},
    {"From": "DSN", "TO": "FUO"},
    {"From": "ENY", "TO": "NAY"},
    {"From": "FUG", "TO": "NAY"},
    {"From": "FUG", "TO": "SZX"},
    {"From": "FUO", "TO": "ZHA"},
    {"From": "FUO", "TO": "PVG"},
    {"From": "FUO", "TO": "DSN"},
    {"From": "FUO", "TO": "NAY"},
    {"From": "FUO", "TO": "TXN"},
    # {"From": "HAK", "TO": "NAY"},
    {"From": "HET", "TO": "NAY"},
    {"From": "HLD", "TO": "NAY"},
    {"From": "HLD", "TO": "HLH"},
    {"From": "HLH", "TO": "NAY"},
    {"From": "HLH", "TO": "HLD"},
    {"From": "HNY", "TO": "NAY"},
    {"From": "HRB", "TO": "NAY"},
    {"From": "HRB", "TO": "TGO"},
    {"From": "HSN", "TO": "NAY"},
    # {"From": "HUZ", "TO": "NAY"},
    # {"From": "IQN", "TO": "NAY"},
    {"From": "IQN", "TO": "LHW"},
    {"From": "JGN", "TO": "JIC"},
    {"From": "JGN", "TO": "NAY"},
    # {"From": "JIC", "TO": "XIY"},
    {"From": "JIC", "TO": "JGN"},
    {"From": "JIC", "TO": "NAY"},
    # {"From": "JUH", "TO": "NAY"},
    {"From": "JUZ", "TO": "NAY"},
    {"From": "KMG", "TO": "NAY"},
    {"From": "KMG", "TO": "SJW"},
    {"From": "LDS", "TO": "NAY"},
    {"From": "BFJ", "TO": "NAY"},
    # {"From": "CAN", "TO": "NAY"},
    {"From": "CIF", "TO": "NAY"},
    {"From": "CIH", "TO": "NAY"},
    {"From": "LHW", "TO": "NAY"},
    #

    {"From": "LHW", "TO": "IQN"},
    {"From": "LYG", "TO": "NAY"},
    {"From": "LYI", "TO": "NAY"},
    {"From": "NAY", "TO": "CTU"},
    {"From": "NAY", "TO": "HRB"},
    {"From": "NAY", "TO": "HET"},
    {"From": "NAY", "TO": "YIE"},
    {"From": "NAY", "TO": "NNY"},
    {"From": "NAY", "TO": "DSN"},
    {"From": "NAY", "TO": "ACX"},
    {"From": "NAY", "TO": "HLD"},
    # {"From": "NAY", "TO": "BFJ"},
    {"From": "NAY", "TO": "NZH"},
    {"From": "NAY", "TO": "XFN"},
    {"From": "NAY", "TO": "TXN"},
    # {"From": "NAY", "TO": "CAN"},
    {"From": "NAY", "TO": "BAV"},
    # {"From": "NAY", "TO": "HUZ"},
    {"From": "NAY", "TO": "LDS"},
    {"From": "NAY", "TO": "XMN"},
    {"From": "NAY", "TO": "ENY"},
    {"From": "NAY", "TO": "TGO"},
    {"From": "NAY", "TO": "LHW"},
    {"From": "NAY", "TO": "DLC"},
    {"From": "NAY", "TO": "KMG"},
    # {"From": "NAY", "TO": "SYX"},
    # {"From": "NAY", "TO": "XNN"},
    # {"From": "NAY", "TO": "PVG"},
    {"From": "NAY", "TO": "RLK"},
    {"From": "NAY", "TO": "SHA"},
    {"From": "NAY", "TO": "CIF"},
    {"From": "NAY", "TO": "CIH"},
    {"From": "NAY", "TO": "DAT"},
    {"From": "NAY", "TO": "FUG"},
    {"From": "NAY", "TO": "FUO"},
    # {"From": "NAY", "TO": "HAK"},
    {"From": "NAY", "TO": "HLH"},
    {"From": "NAY", "TO": "HNY"},
    {"From": "NAY", "TO": "HSN"},
    {"From": "NAY", "TO": "IQN"},
    {"From": "NAY", "TO": "AVA"},
    {"From": "NAY", "TO": "JGN"},
    {"From": "NAY", "TO": "JIC"},
    #{"From": "NAY", "TO": "JUH"},
    {"From": "NAY", "TO": "JUZ"},
    #





    {"From": "NAY", "TO": "NGB"},
    {"From": "NAY", "TO": "SZX"},
    {"From": "NAY", "TO": "LYG"},
    {"From": "NAY", "TO": "LYI"},
    # {"From": "NAY", "TO": "URC"},
    {"From": "NAY", "TO": "UYN"},
    # {"From": "NAY", "TO": "WNZ"},
    {"From": "NAY", "TO": "XIL"},
    {"From": "NAY", "TO": "NDG"},
    {"From": "NDG", "TO": "NAY"},
    {"From": "NGB", "TO": "NAY"},
    {"From": "NKG", "TO": "DSN"},
    {"From": "NNY", "TO": "NAY"},
    {"From": "NZH", "TO": "NAY"},
    # {"From": "PEK", "TO": "DQA"},
    {"From": "PVG", "TO": "FUO"},
    # {"From": "PVG", "TO": "NAY"},
    {"From": "PVG", "TO": "SJW"},
    {"From": "RLK", "TO": "NAY"},
    {"From": "SHA", "TO": "NAY"},
    {"From": "SHA", "TO": "SJW"},
    {"From": "SJW", "TO": "CTU"},
    {"From": "SJW", "TO": "DLC"}, #add
    {"From": "SJW", "TO": "DSN"},
    {"From": "SJW", "TO": "KMG"}, #add
    {"From": "SJW", "TO": "PVG"},
    {"From": "SJW", "TO": "SHA"},
    {"From": "SJW", "TO": "SZX"},
    # {"From": "SYX", "TO": "NAY"},
    {"From": "SZX", "TO": "FUG"},
    {"From": "SZX", "TO": "NAY"},
    # {"From": "SZX", "TO": "SJW"},
    # {"From": "TGO", "TO": "NAY"},
    {"From": "TXN", "TO": "NAY"},
    {"From": "TXN", "TO": "FUO"},
    # {"From": "URC", "TO": "NAY"},
    {"From": "UYN", "TO": "NAY"},
    # {"From": "WNZ", "TO": "NAY"},
    {"From": "XFN", "TO": "NAY"},
    {"From": "XIL", "TO": "NAY"},
    # {"From": "XIY", "TO": "JIC"},
    {"From": "XMN", "TO": "NAY"},
    # {"From": "XNN", "TO": "DSN"},
    # {"From": "XNN", "TO": "NAY"},
    {"From": "YIE", "TO": "NAY"},
    {"From": "ZHA", "TO": "FUO"},
]



